# Generated by Django 3.1.1 on 2020-10-04 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopslider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدر ها'},
        ),
    ]
