# Generated by Django 3.1.1 on 2020-10-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopslider', '0002_auto_20201004_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='img',
            new_name='image',
        ),
    ]
