# Generated by Django 3.1.1 on 2020-10-10 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoporder', '0002_auto_20201010_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoporder.order', verbose_name='سبد خرید'),
        ),
    ]
