# Generated by Django 3.1.1 on 2020-10-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsetting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='copy_right',
            field=models.CharField(max_length=100, verbose_name='کپی رایت'),
        ),
    ]
