# Generated by Django 3.1.1 on 2020-10-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcategory', '0001_initial'),
        ('shopproducts', '0002_auto_20200928_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.ManyToManyField(blank=True, to='shopcategory.ProductCategory', verbose_name='دسته بندی'),
        ),
    ]
