# Generated by Django 3.1.1 on 2020-10-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopproducts', '0004_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='products/gallery', verbose_name='تصویر'),
        ),
    ]
