# Generated by Django 3.1.1 on 2020-10-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopproducts', '0005_auto_20201004_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
    ]
