# Generated by Django 3.1.1 on 2020-10-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopproducts', '0006_auto_20201004_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='visit_count',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
